### ISSUE TITLE
Issue with controls in multiple solution

### ISSUE THREAD

**Issue by Power-Maverick** [MarkMpn/PcfUsageInspector#4]
I have several controls in multiple solution but it always picks Active Solution. What does Active solution means?
Also some controls are in one solution but they also show up under Active solution.

---
- Deployment: Online
- DB Version: 9.1.0.24949
- Connection Controls Version: 1.2021.1.39
- XrmToolBox Version: 1.2020.11.42
- Tool Version: 1.0.2.0

**Comment by MarkMpn** [comment]
I believe Active Solution indicates it's part of the unmanaged layer - are these controls you're building yourself or importing from elsewhere?

It's currently showing the solution the control is originally created in, but I'll see if I can extend that to show a list of all solutions it's part of.

**Comment by Power-Maverick** [comment]
All the control were built by myself and they were created in their respective solutions. Some controls were deployed using `pac pcf push` and some were deployed using `.cdsproj` file. See the attached screenshot where I have mapped the controls to their appropriate solutions. 

![image](https://user-images.githubusercontent.com/36135520/104107725-909c6600-528c-11eb-9e7f-8e16f8929e87.png)
