### ISSUE TITLE
Row highlights on the control

### ISSUE THREAD

**Issue by Power-Maverick** [MarkMpn/PcfUsageInspector#5]
I liked the idea of highlighting the deprecated controls but there are two type of highlights. One is gray and another is red. What is the difference between the two.
Can you add another column or have some UI where you can show the reason why those components are getting highlighted?

---
- Deployment: Online
- DB Version: 9.1.0.24949
- Connection Controls Version: 1.2021.1.39
- XrmToolBox Version: 1.2020.11.42
- Tool Version: 1.0.2.0

**Comment by MarkMpn** [comment]
The red indicates deprecated ones that are in use, while grey is deprecated but not in use. If you hover your mouse over the row the deprecation details should show as a tooltip.
